config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :courts, only: [:index, :show]
    end
  end

  resources :courts, only:[:index, :show, :new, :create, :edit, :update, :destroy]

  get '*page', to: 'courts#index', constraints: ->(req) do
    !req.xhr? && req.format.html?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
  mount_uploader :court_photo, PictureUploader

  validates :name, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  has_many :reviews

  def address
    [street, city, state, country].compact.join(', ')
  end

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end

  # geocoded_by :address
  # after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/courts_controller.rb
class Api::V1::CourtsController < ApplicationController

   def index
     render json: Court.all
   end

   def show
     court = Court.find(params[:id])
     render json: { court: court }
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController

  def index
    @courts = Court.all
  end

  def show
    @court = Court.find(params[:id])
  end

  def  new
    @court = Court.new
  end

  def create
    @court = Court.new(court_params)

    if @court.save
      flash[:notice] = "Basketball Court profile successfully created"
      redirect_to @court
    else
      flash.now[:notice] = "Failed to create court profile"
      render :new
    end
  end

  private

  def court_params
    params.require(:court).permit(:name, :street, :city, :state, :country, :court_photo)
  end

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Please log in to continue"
      redirect_to root_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/courts/index.html.erb
<section class="container">
  <div class="row">
    <ul className="app">
      <% @courts.each do |court| %>
          <div class="column medium-4">
            <a href="/courts/<%= court.id %>">
              <div class="card-panel hoverable">
                <div class="container">
                  <%= court.name %>
                </div>
                <div class="image">
                  <%= image_tag court.court_photo.url.to_s %>
                </div>
              </div>
            </a>
          </div>
      <% end %>
      <div className="add">
        <h3 class="button secondary"><%= link_to "Add a Court", new_court_path %></h3>
      </div>
    </ul>
  </div>
</section>

app/views/courts/new.html.erb
<section class="container">
  <div class="row">
    <h1 className="court-name">Add New Court</h1>
  </div>
  <div class="row">
    <div class="column medium-6 right">
      <%= link_to "Back", courts_path %>
    </div>
  </div>
  <div class="row">
    <form>
      <div class="grid-x grid-padding-x">
        <%= form_for(@court) do |f| %>
        <div class="small-3 cell">
          <label for="right-label"  class="text-right"><%= f.label :name %><label>
        </div>
        <div class="small-9 cell">
          <input type="text" id="right-label" placeholder="Court Name"<%= f.text_field :name %>
        </div>
        <div class="small-3 cell">
          <label for="right-label"  class="text-right"><%= f.label :street %><label>
        </div>
        <div class="small-9 cell">
          <input type="text" id="right-label" placeholder="Street"<%= f.text_field :street %>
        </div>
        <div class="small-3 cell">
          <label for="right-label"  class="text-right"><%= f.label :city %><label>
        </div>
        <div class="small-9 cell">
          <input type="text" id="right-label" placeholder="City"<%= f.text_field :city %>
        </div>
        <div class="small-3 cell">
          <label for="right-label"  class="text-right"><%= f.label :state %><label>
        </div>
        <div class="small-9 cell">
          <input type="text" id="right-label" placeholder="State"<%= f.text_field :state %>
        </div>
        <div class="small-3 cell">
          <label for="right-label"  class="text-right"><%= f.label :country %><label>
        </div>
        <div class="small-9 cell">
          <input type="text" id="right-label" placeholder="Country"<%= f.text_field :country %>
        </div>
      </div>
      <div class="row">
        <div class="column small-6 large-centered">
          <%= f.file_field :court_photo %>
        </div>
      </div>
      <div className="submit">
        <%= f.submit "Add Court" %>
      </div>
      <% end %>
    </form>
  </div>
</section>

app/views/courts/show.html.erb
<div id="app">

</div>

app/views/homes/index.html.erb
<div id="app" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find A Court</title>
  <!-- Import FontAwesome -->
  <script src="https://kit.fontawesome.com/1a3195be62.js" crossorigin="anonymous"></script>
  
  <!-- Import Foundation -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.4.3/dist/css/foundation.min.css" integrity="sha256-GSio8qamaXapM8Fq9JYdGNTvk/dgs+cMLgPeevOYEx0= sha384-wAweiGTn38CY2DSwAaEffed6iMeflc0FMiuptanbN4J+ib+342gKGpvYRWubPd/+ sha512-QHEb6jOC8SaGTmYmGU19u2FhIfeG+t/hSacIWPpDzOp5yygnthL3JwnilM7LM1dOAbJv62R+/FICfsrKUqv4Gg==" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.4.3/dist/js/foundation.min.js" integrity="sha256-mRYlCu5EG+ouD07WxLF8v4ZAZYCA6WrmdIXyn1Bv9Vk= sha384-KzKofw4qqetd3kvuQ5AdapWPqV1ZI+CnfyfEwZQgPk8poOLWaabfgJOfmW7uI+AV sha512-0gHfaMkY+Do568TgjJC2iMAV0dQlY4NqbeZ4pr9lVUTXQzKu8qceyd6wg/3Uql9qA2+3X5NHv3IMb05wb387rA==" crossorigin="anonymous"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">BreakableToyFinal</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>